#playbook.yml
---
- name: Create Arch Linux Base Block Device
  hosts: localhost
  gather_facts: true
  vars:
    ansible_root: /mnt/external-backup/ansible
  tasks:
    - ansible.builtin.import_role:
        name: enc_blkdev_provision
      vars:
        enc_blkdev_provision_device_name: arch_linux_base
        enc_blkdev_provision_mounts_location: /mnt/managed-mounts
        enc_blkdev_provison_storage_path: /mnt/external-backup/panda-pool
        enc_blkdev_provision_storage_size_mb: 2048

    - ansible.builtin.import_role:
        name: arch_linux_provision
      vars:
        arch_linux_provision_iso_name: PandaLinux
        arch_linux_provision_iso_label: panda_linux
        arch_linux_provision_iso_install_dir: pandaiso
        arch_linux_provision_iso_profile: Test
        arch_linux_provision_iso_website: github.com/SuperPanda
        arch_linux_provision_projects_path: "{{ ansible_root }}/projects"
        arch_linux_provision_project_name: pandalinux
        arch_linux_provision_profile_name: test
        arch_linux_provision_src_profile: baseline
        arch_linux_provision_work_directory: work
        arch_linux_provision_output_directory: out
        #arch_linux_provision_packages:
        #  - base
        arch_linux_provision_keys_location: "{{ ansible_root }}/keys"
      tags: [ 'never', 'build' ]

    - ansible.builtin.import_role:
        name: kvm_provision
      vars:
        kvm_provision_vm_name: pandalinux-test
        kvm_provision_max_memory: 4096
        kvm_provision_memory: 2048
        kvm_provision_num_cpus: 2
        kvm_provision_disks:
          - src_file: /mnt/external-backup/ansible/projects/pandalinux/out/test/pandalinux-test-2023.11.07-x86_64.iso
            target_dev: vda
            boot_order: 1
          - src_file: /mnt/external-backup/panda-pool/arch_linux_base.img
            target_dev: vdb

        kvm_provision_net_interfaces:
          - type: bridge
            device: service-bridge
            mac_address: CA:FE:C0:FF:EE:99
      tags: [ 'start', 'init' ]
          




 
