---
# tasks file for enc_blkdev_provision
- debug:
    msg: Loop device = {{ LOOP_DEV }}, Key file = {{ BLOCK_IMAGE_KEY_PATH }}, Device name = {{ DEVICE_NAME }}
  tags:
    - debug
    - never

- name: Open LUKS Device
  community.crypto.luks_device:
    device: "{{ LOOP_DEV }}"
    state: "opened"
    keyfile: "{{ BLOCK_IMAGE_KEY_PATH }}"
    name: "{{ DEVICE_NAME }}"


  
