---
- name: Remove snapshot mount
  ansible.posix.mount:
    path: "{{ SNAPSHOTS_LOCATION }}"
    state: unmounted
- name: Remove mount
  ansible.posix.mount:
    path: "{{ MOUNT_PATH }}"
    state: unmounted
