---
# tasks file for enc_blkdev_provision
- debug:
    msg: Block file = {{ BLOCK_IMAGE_FILE_PATH }}, Size = {{ STORAGE_SIZE_MB }}MB
  tags:
    - debug
    - never


- name: Initialise Block Device Image File with Random Data
  community.general.filesize:
    path: "{{ BLOCK_IMAGE_FILE_PATH }}"
    size: "{{ STORAGE_SIZE_MB }} MiB"
    source: /dev/urandom
    mode: u=rw,g=,o=


- name: Create 2048 byte keyfile
  community.general.filesize:
    path: "{{ BLOCK_IMAGE_KEY_PATH }}"
    source: /dev/urandom
    size: 4
    blocksize: 512
    mode: u=r,g=,o=

 #- name: Initialise Block Device Image File with Random Data
 #  args:
 #    creates: "{{ BLOCK_IMAGE_FILE_PATH }}"
 #  ansible.builtin.command: dd if=/dev/urandom of="{{ BLOCK_IMAGE_FILE_PATH }}" bs=1M count="{{ STORAGE_SIZE_MB }}"


 #- name: Create 2048 byte keyfile
 #  args:
 #    creates: "{{ BLOCK_IMAGE_FILE_PATH }}"
 #  shell: |
 #    dd bs=512 count=4 if=/dev/random of="{{ BLOCK_IMAGE_KEY_PATH }}" iflag=fullblock
 #    chmod -v 0600 "{{ BLOCK_IMAGE_KEY_PATH }}"




  
