---
# tasks file for enc_blkdev_provision
- name: Remove loop device
  when: LOOP_DEV is defined
  ansible.builtin.command: losetup -d "{{ LOOP_DEV }}"

- name: Check for existance of backing file
  when: LOOP_DEV is not defined
  ansible.builtin.stat:
    path: "{{ BLOCK_IMAGE_FILE_PATH }}"
  register: back_file

- name: Find active loop device
  when: back_file.stat.exists is defined and back_file.stat.exists == True
  ansible.builtin.command: losetup --find --nooverlap --show "{{ BLOCK_IMAGE_FILE_PATH }}"
  register: loopdev

- name: Close loop device
  when: back_file.stat.exists is defined and back_file.stat.exists == True
  ansible.builtin.command: losetup -d "{{ loopdev.stdout }}"


  
