---
- name: Unmount filesystem
  tags: ['stop', 'remove', 'never']
  ansible.builtin.include_role:
    name: enc_blkdev_provision
    tasks_from: remove_fs_mount
    apply:
      tags: ['always']

- name: Stop Encrypted Container
  tags: ['stop', 'remove', 'never']
  ansible.builtin.include_role:
    name: enc_blkdev_provision
    tasks_from: close_crypt
    apply:
      tags: ['always']

- name: Close Loop Devices
  tags: ['stop', 'remove', 'never']
  ansible.builtin.include_role:
    name: enc_blkdev_provision
    tasks_from: remove_block_loop_dev
    apply:
      tags: ['always']


